#!/usr/bin/env ruby

submodules = [
  "https://github.com/tpope/vim-cucumber.git",
  "https://github.com/tpope/vim-endwise.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/tpope/vim-haml.git",
  "https://github.com/tpope/vim-rails.git",
  "https://github.com/tpope/vim-unimpaired.git",
  "https://github.com/vim-scripts/Puppet-Syntax-Highlighting",
  "https://github.com/scrooloose/nerdcommenter.git",
  "https://github.com/scrooloose/nerdtree.git",
  "https://github.com/Lokaltog/vim-powerline.git",
  "https://github.com/tpope/vim-surround.git",
  "https://github.com/Raimondi/delimitMate.git",
]

submodules.each do |bundle|
  fname = File.basename(bundle, '.*')
  name = fname.gsub(/^vim[-_]|[-_.]vim$/,'')
  if File.exist? "bundle/#{name}"
    `cd bundle/#{name} && git pull`
    message = "Updating #{fname} bundle submodule"
  else
    `git submodule add #{bundle} bundle/#{name}`
    message = "Install #{fname} bundle as a submodule"
  end
  `git add bundle/#{name}`
  `git commit -m '#{message}'`
end

# {
#    :json => 1945, :ftdetect
# }
vimscripts_id =[1147]

vimscripts_id.each do |id|
#  http://www.vim.org/scripts/download_script.php?src_id=15905
end
